### Homework 6
#### Abhishek Kumar
#### A20467982

In [167]:
import numpy as np
import pandas as pd
import math
from sklearn import metrics

### 2.1 Problem 1  

In [168]:
user_columns = ['user_id',
             'age',
             'gender',
             'occupation',
             'zip_code']

users = pd.read_csv(r'C:\Users\stuar\Documents\College\Data Mining\Assignment\ml-100k/u.user',sep='|',
                    names=user_columns)
rating_columns = ['user_id',
               'movie_id',
               'rating',
               'timestamp']

ratings = pd.read_csv(r'C:\Users\stuar\Documents\College\Data Mining\Assignment\ml-100k/u.data',sep='\t',
                      names=rating_columns)
item_columns = ['movie id',
             'movie title',
             'release date',
             'video release date',
             'IMDb URL',
             'Unknown',
             'Action',
             'Adventure',
             'Animation',
             'Childrens',
             'Comedy',
             'Crime',
             'Documentary',
             'Drama',
             'Fantasy',
             'FilmNoir',
             'Horror',
             'Musical',
             'Mystery',
             'Romance',
             'SciFi',
             'Thriller',
             'War',
             'Western']

items = pd.read_csv(r'C:\Users\stuar\Documents\College\Data Mining\Assignment\ml-100k/u.item',sep='|',
                    names=item_columns,encoding='latin-1')


In [169]:
users.head()

user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [170]:
ratings.head()

user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [171]:
items.head()

movie id        movie title release date  video release date  \
0         1   Toy Story (1995)  01-Jan-1995                 NaN   
1         2   GoldenEye (1995)  01-Jan-1995                 NaN   
2         3  Four Rooms (1995)  01-Jan-1995                 NaN   
3         4  Get Shorty (1995)  01-Jan-1995                 NaN   
4         5     Copycat (1995)  01-Jan-1995                 NaN   

                                            IMDb URL  Unknown  Action  \
0  http://us.imdb.com/M/title-exact?Toy%20Story%2...        0       0   
1  http://us.imdb.com/M/title-exact?GoldenEye%20(...        0       1   
2  http://us.imdb.com/M/title-exact?Four%20Rooms%...        0       0   
3  http://us.imdb.com/M/title-exact?Get%20Shorty%...        0       1   
4  http://us.imdb.com/M/title-exact?Copycat%20(1995)        0       0   

   Adventure  Animation  Childrens  ...  Fantasy  FilmNoir  Horror  Musical  \
0          0          1          1  ...        0         0       0        0   
1          1          0          0  ...        0         0       0        0   
2          0          0          0  ...        0         0       0        0   
3          0          0          0  ...        0         0       0        0   
4          0          0          0  ...        0         0       0        0   

   Mystery  Romance  SciFi  Thriller  War  Western  
0        0        0      0         0    0        0  
1        0        0      0         1    0        0  
2        0        0      0         1    0        0  
3        0        0      0         0    0        0  
4        0        0      0         1    0        0  

[5 rows x 24 columns]

In [172]:
user1= ratings[(ratings["user_id"]==200)]
print("User1 ID = 200\n")
print(user1.head())
print("\nUser1 ID = 15\n")
user2 = ratings[(ratings["user_id"]==15)]
print(user2.head())

User1 ID = 200

     user_id  movie_id  rating  timestamp
12       200       222       5  876042340
189      200       673       5  884128554
243      200       318       5  884128458
326      200       304       5  876041644
367      200        96       5  884129409

User1 ID = 15

      user_id  movie_id  rating  timestamp
206        15       405       2  879455957
642        15       749       1  879455311
708        15        25       3  879456204
1208       15       331       3  879455166
1365       15       222       3  879455730


In [173]:
item_pref = items[94:95]
item_pref.head()

movie id     movie title release date  video release date  \
94        95  Aladdin (1992)  01-Jan-1992                 NaN   

                                             IMDb URL  Unknown  Action  \
94  http://us.imdb.com/M/title-exact?Aladdin%20(1992)        0       0   

    Adventure  Animation  Childrens  ...  Fantasy  FilmNoir  Horror  Musical  \
94          0          1          1  ...        0         0       0        1   

    Mystery  Romance  SciFi  Thriller  War  Western  
94        0        0      0         0    0        0  

[1 rows x 24 columns]

In [174]:
utility_in = ratings.pivot(index='user_id',
                        columns='movie_id',
                        values='rating')

utility_in.head()

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
1          5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2          4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0  ...   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
5          4.0   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   

movie_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                               
1          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
5          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[5 rows x 1682 columns]

In [175]:
average_User = utility_in.mean(axis=1)
average_User.head()

user_id
1    3.610294
2    3.709677
3    2.796296
4    4.333333
5    2.874286
dtype: float64

In [176]:
centered_data = utility_in - average_User
centered_data = centered_data.where((pd.notnull(centered_data)),0)
utility_New = utility_in.where((pd.notnull(utility_in)),0)
centered_data.head()

1         2         3         4         5         6         7     \
user_id                                                                         
1        1.389706 -0.709677  1.203704 -1.333333  0.125714  1.364929  0.034739   
2        0.389706  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
5        0.389706 -0.709677  0.000000  0.000000  0.000000  0.000000  0.000000   

            8         9         10    ...  1673  1674  1675  1676  1677  1678  \
user_id                               ...                                       
1       -2.79661  0.727273 -1.206522  ...   0.0   0.0   0.0   0.0   0.0   0.0   
2        0.00000  0.000000 -2.206522  ...   0.0   0.0   0.0   0.0   0.0   0.0   
3        0.00000  0.000000  0.000000  ...   0.0   0.0   0.0   0.0   0.0   0.0   
4        0.00000  0.000000  0.000000  ...   0.0   0.0   0.0   0.0   0.0   0.0   
5        0.00000  0.000000  0.000000  ...   0.0   0.0   0.0   0.0   0.0   0.0   

         1679  1680  1681  1682  
user_id                          
1         0.0   0.0   0.0   0.0  
2         0.0   0.0   0.0   0.0  
3         0.0   0.0   0.0   0.0  
4         0.0   0.0   0.0   0.0  
5         0.0   0.0   0.0   0.0  

[5 rows x 1682 columns]

### Item/Movie 95. 

In [177]:
feat_pref = item_pref.iloc[:,5:24]
feat_pref.head()

Unknown  Action  Adventure  Animation  Childrens  Comedy  Crime  \
94        0       0          0          1          1       1      0   

    Documentary  Drama  Fantasy  FilmNoir  Horror  Musical  Mystery  Romance  \
94            0      0        0         0       0        1        0        0   

    SciFi  Thriller  War  Western  
94      0         0    0        0

In [178]:
profile_item = items.iloc[:,5:24]
profile_item.head()

Unknown  Action  Adventure  Animation  Childrens  Comedy  Crime  \
0        0       0          0          1          1       1      0   
1        0       1          1          0          0       0      0   
2        0       0          0          0          0       0      0   
3        0       1          0          0          0       1      0   
4        0       0          0          0          0       0      1   

   Documentary  Drama  Fantasy  FilmNoir  Horror  Musical  Mystery  Romance  \
0            0      0        0         0       0        0        0        0   
1            0      0        0         0       0        0        0        0   
2            0      0        0         0       0        0        0        0   
3            0      1        0         0       0        0        0        0   
4            0      1        0         0       0        0        0        0   

   SciFi  Thriller  War  Western  
0      0         0    0        0  
1      0         1    0        0  
2      0         1    0        0  
3      0         0    0        0  
4      0         1    0        0

In [179]:
user_profile = np.dot(utility_New,profile_item)

print("\nUser Profile:\n\n", user_profile)



User Profile:

 [[  4. 250. 123. ... 188.  92.  22.]
 [  0.  38.  13. ...  43.  11.   0.]
 [  0.  39.  14. ...  53.  14.   0.]
 ...
 [  0.  38.  27. ...  28.   5.   0.]
 [  0.  74.  52. ...  80.  47.  14.]
 [  0. 227. 114. ... 134.  53.  23.]]


### User Profile on centered data (by user rating) for both users 200 and 15 

In [189]:
user_profile_200 = user_profile[199]
print("\nUser-Profile of User 200):\n\n", user_profile_200)

user_profile_15 = user_profile[14]
print("\nUser-Profile of User 15):\n\n", user_profile_15)


User-Profile of User 200):

 [  0. 332. 235.  66. 166. 193.  37.   2. 251.  41.  10.  44.  72.  15.
 148. 188. 201.  73.  16.]

User-Profile of User 15):

 [  0.  59.  36.   2.  13.  75.  15.   0. 153.  10.   6.   2.   4.  17.
  86.  32.  59.  34.   0.]


### Cosine Similarity

In [181]:
cosine = metrics.pairwise.cosine_similarity(user_profile,feat_pref)

In [182]:
print("Cosine Similarity (User 200):", cosine[199])
print("Cosine Similarity (User 15) :", cosine[14])

Cosine Similarity (User 200): [0.38745727]
Cosine Similarity (User 15) : [0.21517341]


### Distance between the user's preferences and the item/movie 95. 

In [183]:
print("Cosine Distance (User 200):", 1-cosine[199])
print("Cosine Distance (User 15) :", 1-cosine[14])

Cosine Distance (User 200): [0.61254273]
Cosine Distance (User 15) : [0.78482659]


### A recommender system would suggest movie 95 to User 200 .

### 2.2 Problem 2  

In [184]:
utility_2 = utility_in.where((pd.notnull(utility_in)),0)
user1 = utility_2.iloc[:1,]
user1.head()

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
1          5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   

movie_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                               
1          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[1 rows x 1682 columns]

### Utility Matrix 

In [185]:
user2 = utility_2.iloc[1:,]
user2.head()

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
2          4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  ...   
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
5          4.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
6          4.0   0.0   0.0   0.0   0.0   0.0   2.0   4.0   4.0   0.0  ...   

movie_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                               
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 1682 columns]

### 10 most similar users for user 1 based on cosine similarity of the centered user ratings data

In [186]:
cosine = metrics.pairwise.cosine_similarity(user1,user2)
indices = np.argpartition(cosine, -10, axis=1)[:, -10:]
print(indices)

[[274 736 427 301 455 266  90 862 433 914]]


### Expected rating for item 508 for user 1

In [188]:
print("\nExpected rating for the item 508 for user 1: \n")
count = 0
ratings = [0,0,0,0,0,0,0,0,0,0]
for i in range(len(indices[0])):
    ratings[i] = user2[508][indices[0][i]]
    if ratings[i] != 0.0:
        count+=1
sum = math.fsum(ratings)
Average = sum/count
print("Average: ",Average)


Expected rating for the item 508 for user 1: 

Average:  4.0
