In [2]:
import numpy as np

In [3]:
from sklearn.impute import SimpleImputer

In [4]:
import pandas as pd

In [5]:
import matplotlib.pyplot as plt

In [6]:
column_names = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'year', 'origin', 'name']

In [7]:
df= pd.read_csv(r"C:\Users\stuar\Downloads\auto-mpg.data",delim_whitespace=True, names=column_names)

In [8]:
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0      130.0  3504.0          12.0    70   
1  15.0          8         350.0      165.0  3693.0          11.5    70   
2  18.0          8         318.0      150.0  3436.0          11.0    70   
3  16.0          8         304.0      150.0  3433.0          12.0    70   
4  17.0          8         302.0      140.0  3449.0          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [9]:
df['horsepower'].unique()

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.00', '97.00', '85.00',
       '88.00', '46.00', '87.00', '90.00', '113.0', '200.0', '210.0',
       '193.0', '?', '100.0', '105.0', '175.0', '153.0', '180.0', '110.0',
       '72.00', '86.00', '70.00', '76.00', '65.00', '69.00', '60.00',
       '80.00', '54.00', '208.0', '155.0', '112.0', '92.00', '145.0',
       '137.0', '158.0', '167.0', '94.00', '107.0', '230.0', '49.00',
       '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
       '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
       '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0',
       '108.0', '68.00', '58.00', '149.0', '89.00', '63.00', '48.00',
       '66.00', '139.0', '103.0', '125.0', '133.0', '138.0', '135.0',
       '142.0', '77.00', '62.00', '132.0', '84.00', '64.00', '74.00',
       '116.0', '82.00'], dtype=object)

In [10]:
horsepower_miss= df[df.horsepower=='?'].index
df.loc[horsepower_miss]

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
32   25.0          4          98.0          ?  2046.0          19.0    71   
126  21.0          6         200.0          ?  2875.0          17.0    74   
330  40.9          4          85.0          ?  1835.0          17.3    80   
336  23.6          4         140.0          ?  2905.0          14.3    80   
354  34.5          4         100.0          ?  2320.0          15.8    81   
374  23.0          4         151.0          ?  3035.0          20.5    82   

     origin                  name  
32        1            ford pinto  
126       1         ford maverick  
330       2  renault lecar deluxe  
336       1    ford mustang cobra  
354       2           renault 18i  
374       1        amc concord dl

In [11]:
df.replace("?", np.nan, inplace = True)

In [12]:
df.loc[horsepower_miss]

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
32   25.0          4          98.0        NaN  2046.0          19.0    71   
126  21.0          6         200.0        NaN  2875.0          17.0    74   
330  40.9          4          85.0        NaN  1835.0          17.3    80   
336  23.6          4         140.0        NaN  2905.0          14.3    80   
354  34.5          4         100.0        NaN  2320.0          15.8    81   
374  23.0          4         151.0        NaN  3035.0          20.5    82   

     origin                  name  
32        1            ford pinto  
126       1         ford maverick  
330       2  renault lecar deluxe  
336       1    ford mustang cobra  
354       2           renault 18i  
374       1        amc concord dl

#### changed horsepower value to NaN

In [13]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
year              int64
origin            int64
name             object
dtype: object

In [14]:
#df.loc[horsepower_miss, 'horsepower'] = float('nan')
df.horsepower = df.horsepower.apply(pd.to_numeric)

In [15]:
df['horsepower'].unique()

array([130., 165., 150., 140., 198., 220., 215., 225., 190., 170., 160.,
        95.,  97.,  85.,  88.,  46.,  87.,  90., 113., 200., 210., 193.,
        nan, 100., 105., 175., 153., 180., 110.,  72.,  86.,  70.,  76.,
        65.,  69.,  60.,  80.,  54., 208., 155., 112.,  92., 145., 137.,
       158., 167.,  94., 107., 230.,  49.,  75.,  91., 122.,  67.,  83.,
        78.,  52.,  61.,  93., 148., 129.,  96.,  71.,  98., 115.,  53.,
        81.,  79., 120., 152., 102., 108.,  68.,  58., 149.,  89.,  63.,
        48.,  66., 139., 103., 125., 133., 138., 135., 142.,  77.,  62.,
       132.,  84.,  64.,  74., 116.,  82.])

In [16]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight          float64
acceleration    float64
year              int64
origin            int64
name             object
dtype: object

#### Data type of horsepower changed to float from object type

In [17]:
mean_mpg=df['mpg'].astype('float').mean(axis=0)
median_mpg=df['mpg'].astype('float').median(axis=0)
mode_mpg=df['mpg'].astype('float').mode()
print("Mean of mpg:", mean_mpg)
print("Median of mpg:", median_mpg)
print("Mode of mpg:", mode_mpg)

Mean of mpg: 23.514572864321607
Median of mpg: 23.0
Mode of mpg: 0    13.0
dtype: float64


In [18]:
mean_cylinder=df['cylinders'].astype('float').mean(axis=0)
median_cylinder=df['cylinders'].astype('float').median(axis=0)
mode_cylinder=df['cylinders'].astype('float').mode()
print("Mean of cylinder:", mean_cylinder)
print("Median of cylinder:", median_cylinder)
print("Mode of cylinder:", mode_cylinder)

Mean of cylinder: 5.454773869346734
Median of cylinder: 4.0
Mode of cylinder: 0    4.0
dtype: float64


In [19]:
mean_displace=df['displacement'].astype('float').mean(axis=0)
median_displace=df['displacement'].astype('float').median(axis=0)
mode_displace=df['displacement'].astype('float').mode()
print("Mean of displacement:", mean_displace)
print("Median of displacement:", median_displace)
print("Mode of displacement:", mode_displace)

Mean of displacement: 193.42587939698493
Median of displacement: 148.5
Mode of displacement: 0    97.0
dtype: float64


In [20]:
mean_horsepower=df['horsepower'].astype('float').mean(axis=0)
median_horsepower=df['horsepower'].astype('float').median(axis=0)
mode_horsepower=df['horsepower'].astype('float').mode()
print("Mean of horsepower:", mean_horsepower)
print("Median of horsepower:", median_horsepower)
print("Mode of horsepower:", mode_horsepower)

Mean of horsepower: 104.46938775510205
Median of horsepower: 93.5
Mode of horsepower: 0    150.0
dtype: float64


In [21]:
mean_weight=df['weight'].astype('float').mean(axis=0)
median_weight=df['weight'].astype('float').median(axis=0)
mode_weight=df['weight'].astype('float').mode()
print("Mean of weight:", mean_weight)
print("Median of weight:", median_weight)
print("Mode of weight:", mode_weight)

Mean of weight: 2970.424623115578
Median of weight: 2803.5
Mode of weight: 0    1985.0
1    2130.0
dtype: float64


In [26]:
mean_acc=df['acceleration'].astype('float').mean(axis=0)
median_acc=df['acceleration'].astype('float').median(axis=0)
mode_acc=df['acceleration'].astype('float').mode()
print("Mean of acceleration:", mean_acc)
print("Median of acceleration:", median_acc)
print("Mode of acceleration:", mode_acc)

Mean of acceleration: 15.568090452261307
Median of acceleration: 15.5
Mode of acceleration: 0    14.5
dtype: float64


In [27]:
mean_yr=df['year'].astype('float').mean(axis=0)
median_yr=df['year'].astype('float').median(axis=0)
mode_yr=df['year'].astype('float').mode()
print("Mean of year:", mean_yr)
print("Median of year:", median_yr)
print("Mode of year:", mode_yr)

Mean of year: 76.01005025125629
Median of year: 76.0
Mode of year: 0    73.0
dtype: float64


In [28]:
mean_origin=df['origin'].astype('float').mean(axis=0)
median_origin=df['origin'].astype('float').median(axis=0)
mode_origin=df['origin'].astype('float').mode()
print("Mean of origin:", mean_origin)
print("Median of origin:", median_origin)
print("Mode of origin:", mode_origin)

Mean of origin: 1.5728643216080402
Median of origin: 1.0
Mode of origin: 0    1.0
dtype: float64


# Replacing Missing Value Nan of 'horsepower' with overall Mean, Median and Mode

### Variance with mean

In [37]:
m = df['horsepower'].mean()
df.loc[horsepower_miss, 'horsepower'] = m
variance = df['horsepower'].var()
print("Mean Variance: ", variance)

Mean Variance:  1459.178219352601


In [30]:
df['horsepower'].unique()

array([130.        , 165.        , 150.        , 140.        ,
       198.        , 220.        , 215.        , 225.        ,
       190.        , 170.        , 160.        ,  95.        ,
        97.        ,  85.        ,  88.        ,  46.        ,
        87.        ,  90.        , 113.        , 200.        ,
       210.        , 193.        , 104.46938776, 100.        ,
       105.        , 175.        , 153.        , 180.        ,
       110.        ,  72.        ,  86.        ,  70.        ,
        76.        ,  65.        ,  69.        ,  60.        ,
        80.        ,  54.        , 208.        , 155.        ,
       112.        ,  92.        , 145.        , 137.        ,
       158.        , 167.        ,  94.        , 107.        ,
       230.        ,  49.        ,  75.        ,  91.        ,
       122.        ,  67.        ,  83.        ,  78.        ,
        52.        ,  61.        ,  93.        , 148.        ,
       129.        ,  96.        ,  71.        ,  98.  

### Variance with median

In [36]:
df.loc[horsepower_miss, 'horsepower'] = float(df.horsepower.median())
variance = df['horsepower'].var()
print('Median Variance: ',variance)

Median Variance:  1460.5126893915422


In [32]:
df['horsepower'].unique()

array([130., 165., 150., 140., 198., 220., 215., 225., 190., 170., 160.,
        95.,  97.,  85.,  88.,  46.,  87.,  90., 113., 200., 210., 193.,
       100., 105., 175., 153., 180., 110.,  72.,  86.,  70.,  76.,  65.,
        69.,  60.,  80.,  54., 208., 155., 112.,  92., 145., 137., 158.,
       167.,  94., 107., 230.,  49.,  75.,  91., 122.,  67.,  83.,  78.,
        52.,  61.,  93., 148., 129.,  96.,  71.,  98., 115.,  53.,  81.,
        79., 120., 152., 102., 108.,  68.,  58., 149.,  89.,  63.,  48.,
        66., 139., 103., 125., 133., 138., 135., 142.,  77.,  62., 132.,
        84.,  64.,  74., 116.,  82.])

### Variance with mode

In [35]:
df.loc[horsepower_miss, 'horsepower'] = int(df.horsepower.mode())
variance = df['horsepower'].var()
print('Mode Variance: ',variance)

Mode Variance:  1490.036125210435


In [34]:
df['horsepower'].unique()

array([130., 165., 150., 140., 198., 220., 215., 225., 190., 170., 160.,
        95.,  97.,  85.,  88.,  46.,  87.,  90., 113., 200., 210., 193.,
       100., 105., 175., 153., 180., 110.,  72.,  86.,  70.,  76.,  65.,
        69.,  60.,  80.,  54., 208., 155., 112.,  92., 145., 137., 158.,
       167.,  94., 107., 230.,  49.,  75.,  91., 122.,  67.,  83.,  78.,
        52.,  61.,  93., 148., 129.,  96.,  71.,  98., 115.,  53.,  81.,
        79., 120., 152., 102., 108.,  68.,  58., 149.,  89.,  63.,  48.,
        66., 139., 103., 125., 133., 138., 135., 142.,  77.,  62., 132.,
        84.,  64.,  74., 116.,  82.])

### Mean result has the lowest variance.

### Small variance represents that the data points tend to be very close to the mean, and to each other. It says that imputation with mean has smaller the variance which shows that data is of similar type than value of median or mode variance.

### We can use Regression method, if there is any correlation between the missing value and other variables, we can  use the predicted value by regressing the missing variable on other variables.